// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBisPCPgX8rYewHLQj5146qhj2LgyPwnF8',
    appId: '1:938066342056:web:24d5e7859efe7cba80d29d',
    messagingSenderId: '938066342056',
    projectId: 'flutter-exercises-844ed',
    authDomain: 'flutter-exercises-844ed.firebaseapp.com',
    storageBucket: 'flutter-exercises-844ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuOi4NdpAUnBUi2BiLXxCUvFqywnM-YdY',
    appId: '1:938066342056:android:75023eaac60e5da380d29d',
    messagingSenderId: '938066342056',
    projectId: 'flutter-exercises-844ed',
    storageBucket: 'flutter-exercises-844ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJSW8bpHa_p8KspGgaOuEAfnTZweusbW8',
    appId: '1:938066342056:ios:cba9786d2d34d85480d29d',
    messagingSenderId: '938066342056',
    projectId: 'flutter-exercises-844ed',
    storageBucket: 'flutter-exercises-844ed.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJSW8bpHa_p8KspGgaOuEAfnTZweusbW8',
    appId: '1:938066342056:ios:cba9786d2d34d85480d29d',
    messagingSenderId: '938066342056',
    projectId: 'flutter-exercises-844ed',
    storageBucket: 'flutter-exercises-844ed.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBisPCPgX8rYewHLQj5146qhj2LgyPwnF8',
    appId: '1:938066342056:web:b00447de0c42d52780d29d',
    messagingSenderId: '938066342056',
    projectId: 'flutter-exercises-844ed',
    authDomain: 'flutter-exercises-844ed.firebaseapp.com',
    storageBucket: 'flutter-exercises-844ed.firebasestorage.app',
  );
}
